import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Container from "./components/container/index";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// forest cupcake
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={inter.className}>
        <Container>
          {children}
        </Container>
      </body>
    </html>
  );
}
